/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.simply.game.threechess.client;

/**
 *
 * @author who
 */
public class DeskButton extends  javax.swing.JButton {

    /**
     * Creates new form DeskButton
     */
    public DeskButton() {
        initComponents();
    }
    private int desk_num;//桌台号
    private int desk_pos;//桌位号

    public int getDesk_num() {
        return desk_num;
    }

    public DeskButton setDesk_num(int desk_num) {
        this.desk_num = desk_num;
        return this;
    }

    public int getDesk_pos() {
        return desk_pos;
    }

    public DeskButton setDesk_pos(int desk_pos) {
        this.desk_pos = desk_pos;
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        setText("空");
        setBorder(null);
        setMargin(new java.awt.Insets(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(30, 30));
        setMinimumSize(new java.awt.Dimension(30, 30));
        setPreferredSize(new java.awt.Dimension(30, 30));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
