/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.simply.game.threechess.client;

import static com.simply.game.threechess.bean.Constants.*;
import com.simply.game.threechess.bean.Desk;
import com.simply.game.threechess.bean.Info;
import com.simply.game.threechess.bean.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.JTextPane;
/**
 *
 * @author who
 */
public class MainGUI extends javax.swing.JFrame{
    
    private Communicator c;
    private User u;
    private List<DeskGUI> duilist;
    private GameGUI gamegui;
    private int desk_num;
    private int desk_position;
    
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        u = new User();
        java.util.Random r = new java.util.Random();
        u.setName("" + r.nextInt());
        this.c = new Communicator("127.0.0.1", 3005, this);
        Info req = new Info();
        req.setAction(ROOM);
        c.send(req);
        
    }
    public void initGameGUI(String turnicon){
        this.gamegui = new GameGUI(this.c, turnicon);
        this.gamegui.setU(this.u);
        this.gamegui.setVisible(true);
    }
    public void initRoom(List<Desk> desks){
       duilist = new ArrayList<DeskGUI>();
        
       //roomGUI1.setBounds(0, 0, 880, 700);
       int i = 0;
       for(Desk d: desks){           
           DeskGUI dui= new DeskGUI();
           dui.getjLabel1().setText("桌子" + (i + 1) );           
           dui.getUser1().setDesk_num(i).setDesk_pos(0);
           dui.getUser2().setDesk_num(i).setDesk_pos(1);
           Info req = new Info();
           for(int j = 0; j< d.getUsers().length; j++){
               req.setAction(DESK);
               req.setDesk_num(i);
               req.setDesk_position(j);
               c.send(req);
           }
           
           dui.getUser1().addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    deskbtnActionPerformed(e);
                }  
           });
           dui.getUser2().addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    deskbtnActionPerformed(e);
                }  
           });
           dui.setBounds(i%4*220, i/4 *110, 200, 100);           
           duilist.add(dui);
           roomGUI1.add(dui);
           i++;

       }
       //this.add(roomGUI1);
       roomGUI1.updateUI(); 
       this.jScrollPane2.updateUI(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomGUI1 = new com.simply.game.threechess.client.RoomGUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 1000));
        setPreferredSize(new java.awt.Dimension(1116, 1000));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(51, 51, 0));
        jTextPane1.setEditable(false);
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("发送");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        roomGUI1.setPreferredSize(new java.awt.Dimension(874, 2800));

        javax.swing.GroupLayout roomGUI1Layout = new javax.swing.GroupLayout(roomGUI1);
        roomGUI1.setLayout(roomGUI1Layout);
        roomGUI1Layout.setHorizontalGroup(
            roomGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        roomGUI1Layout.setVerticalGroup(
            roomGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2800, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(roomGUI1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public GameGUI getGamegui() {
        return gamegui;
    }

    public void setGamegui(GameGUI gamegui) {
        this.gamegui = gamegui;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String msg = jTextField2.getText();
        Info req = new Info();
        req.setAction(CHAT_MSG_TO_ALL);
        req.setChat_msg(u.getName() + "说:" + msg);
        this.c.send(req);
    }//GEN-LAST:event_jButton1ActionPerformed
   private void deskbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DeskButton dtn = (DeskButton)evt.getSource();
        this.desk_num = dtn.getDesk_num();
        Info req = new Info();
        req.setAction(ENTER_DESK);
        req.setDesk_num(dtn.getDesk_num());
        req.setUser(this.u);
        req.setDesk_position(dtn.getDesk_pos());
        this.c.send(req);
        
    } 
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        if(this.jTextField2.hasFocus() && !this.jTextField2.getText().equals("")){
            String msg = jTextField2.getText();
            Info req = new Info();
            req.setAction(CHAT_MSG_TO_ALL);
            req.setChat_msg(u.getName() + "说:" + msg);
            this.c.send(req);
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    public List<DeskGUI> getDuilist() {
        return duilist;
    }

    public void setDuilist(List<DeskGUI> duilist) {
        this.duilist = duilist;
    }

    public int getDesk_position() {
        return desk_position;
    }

    public void setDesk_position(int desk_position) {
        this.desk_position = desk_position;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    public int getDesk_num() {
        return desk_num;
    }

    public void setDesk_num(int desk_num) {
        this.desk_num = desk_num;
    }

    public Communicator getC() {
        return c;
    }

    public void setC(Communicator c) {
        this.c = c;
    }

    public User getU() {
        return u;
    }

    public void setU(User u) {
        this.u = u;
    }

    public JTextPane getjTextPane1() {
        return jTextPane1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private com.simply.game.threechess.client.RoomGUI roomGUI1;
    // End of variables declaration//GEN-END:variables


}
